name: Build and Deploy Antora Documentation


on:
  push:
    branches:
      - main
      - 'feature/day*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install Antora CLI and site generator
        run:  npm install -g @antora/cli @antora/site-generator-default
        
      - name: Build Antora Site
        run:  npx antora playbook.yml
