name: Build and Deploy Antora Documentation


on:
  push:
    branches:
      - main
      - 'feature/day*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/set-node@v2
        with:
          node-version: '22'
      - name: Install Antora
        run:  npm install -g @antora/cli @antora/site-generator-default
      - name: Build Site
        run:  antora playbook.yml
      - name: Deploy to GitHub Pages
        uses:  peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
